### ISSUE TITLE
Thumbs up 

### ISSUE THREAD

**Issue by btok** [moshest/webstorm-settings#1]
Hi Moshe,
No issue or anything like that. Just didnt know where else i can write a good feedback.
Just wanted to send you some good vibes for creating the webstorm coding style config to match the airbnb style.
Interesting that I could not find anything about it and that the predefined styles inside webstorm only match Google or Standard.
So again - a big thank you.
toda raba ! 👍
Ben

(I will close the issue soon or you can once you see it :))

**Comment by moshest** [comment]
Thank you.

**Comment by moshest** [comment]
Nowadays, everyone using [prettier](https://github.com/prettier/prettier) style guide.
I didn't find yet a plugin that use this style.

**Comment by btok** [comment]
Thanks for the tip. 
Actually the biggest benefit in my opinion from those tools are the code-quality checks and not the formating so im not too stressed about moving to prettier (Considering you still probably use Airbnb under the hood for code quality). 
But looking at the big adoption of Prettier from the community, We will probably see something automatic for WebStorm soon. Im always on the lookout for better tools so If I will see something, I will let you know
Cheers !
